# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HelpText.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpText(object):
    def setupUi(self, HelpText):
        HelpText.setObjectName("HelpText")
        HelpText.resize(1079, 816)
        self.centralwidget = QtWidgets.QWidget(HelpText)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(37, 37, 37);    ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.BackFromHelp = QtWidgets.QPushButton(self.frame)
        self.BackFromHelp.setGeometry(QtCore.QRect(20, 710, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.BackFromHelp.setFont(font)
        self.BackFromHelp.setStyleSheet("background-color:rgb(0, 129, 193)")
        self.BackFromHelp.setCheckable(False)
        self.BackFromHelp.setObjectName("BackFromHelp")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 1061, 651))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.frame)
        HelpText.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HelpText)
        self.statusbar.setObjectName("statusbar")
        HelpText.setStatusBar(self.statusbar)

        self.retranslateUi(HelpText)
        QtCore.QMetaObject.connectSlotsByName(HelpText)

    def retranslateUi(self, HelpText):
        _translate = QtCore.QCoreApplication.translate
        HelpText.setWindowTitle(_translate("HelpText", "MainWindow"))
        self.BackFromHelp.setText(_translate("HelpText", "Tillbaka"))
        self.textBrowser.setHtml(_translate("HelpText", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt; color:#00aaff;\">https://www.youtube.com/watch?v=sxOlWtJUBD4</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HelpText = QtWidgets.QMainWindow()
    ui = Ui_HelpText()
    ui.setupUi(HelpText)
    HelpText.show()
    sys.exit(app.exec_())
