# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HelpText.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HelpText(object):

    def setupUi(self, HelpText):
        HelpText.setObjectName("HelpText")
        HelpText.resize(1079, 816)
        self.centralwidget = QtWidgets.QWidget(HelpText)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(37, 37, 37);    ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.BackFromHelp = QtWidgets.QPushButton(self.frame)
        self.BackFromHelp.clicked.connect(lambda: self.toggle_window(HelpText))
        self.BackFromHelp.setGeometry(QtCore.QRect(20, 710, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.BackFromHelp.setFont(font)
        self.BackFromHelp.setStyleSheet("background-color:rgb(0, 129, 193)")
        self.BackFromHelp.setCheckable(False)
        self.BackFromHelp.setObjectName("BackFromHelp")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(0, 10, 1061, 651))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setStyleSheet("border:0")
        self.verticalLayout.addWidget(self.frame)
        HelpText.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HelpText)
        self.statusbar.setObjectName("statusbar")
        HelpText.setStatusBar(self.statusbar)
        self.retranslateUi(HelpText)
        QtCore.QMetaObject.connectSlotsByName(HelpText)

    def retranslateUi(self, HelpText):
        _translate = QtCore.QCoreApplication.translate
        HelpText.setWindowTitle(_translate("HelpText", "Health-Goal"))
        self.BackFromHelp.setText(_translate("HelpText", "Tillbaka"))
        self.textBrowser.setSource(
            QtCore.QUrl.fromLocalFile("html.html"))

    def toggle_window(self, window):
        if window.isVisible():
            window.hide()

        else:
            window.show()
