# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup(object):
    def setupUi(self, popup):
        popup.setObjectName("popup")
        popup.resize(285, 165)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        popup.setFont(font)
        popup.setAutoFillBackground(False)
        popup.setStyleSheet("background-color: rgb(37, 37, 37);\n"
"background-color: rgb(37,37,37);\n"
"\n"
"")
        self.infobutton = QtWidgets.QPushButton(popup)
        self.infobutton.setGeometry(QtCore.QRect(210, 120, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.infobutton.setFont(font)
        self.infobutton.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.infobutton.setObjectName("infobutton")
        self.label_3 = QtWidgets.QLabel(popup)
        self.label_3.setGeometry(QtCore.QRect(40, 50, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font-size: 12px;\n"
"font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 222, 222);\n"
"color: rgb(0, 170, 255);")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(popup)
        QtCore.QMetaObject.connectSlotsByName(popup)

    def retranslateUi(self, popup):
        _translate = QtCore.QCoreApplication.translate
        popup.setWindowTitle(_translate("popup", "Health-Goal"))
        self.infobutton.setText(_translate("popup", "OK"))
        self.label_3.setText(_translate("popup", "Du har X poäng med X dagar kvar"))
